### ISSUE TITLE
`SystemError: Credentials could not be found.` on a public data access comman run

### ISSUE THREAD

**Issue by brunolnetto** [ofek/pypinfo#145]
Hi fellows,

I just installed `pypinfo` and ran the command `pypinfo requests` as you suggested. The following error popped out: 

```
Traceback (most recent call last):
  File "/home/brunolnetto/.local/bin/pypinfo", line 8, in <module>
    sys.exit(pypinfo())
  File "/home/brunolnetto/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/brunolnetto/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/brunolnetto/.local/lib/python3.8/site-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/home/brunolnetto/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brunolnetto/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/brunolnetto/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/brunolnetto/.local/lib/python3.8/site-packages/pypinfo/cli.py", line 168, in pypinfo
    with create_client(get_credentials()) as client:
  File "/home/brunolnetto/.local/lib/python3.8/site-packages/pypinfo/core.py", line 55, in create_client
    raise SystemError('Credentials could not be found.')
SystemError: Credentials could not be found.
``` 

I did not expect to register any credentials. I suspect, this library is helpful for only `PyPI` staff team (command run `pypinfo` output, among others, `-a, --auth TEXT         Path to Google credentials JSON file.`), which means the credential corresponds to the respective BigQuery API key. Nevertheless, I am glad to make this argument, since the documentation claims, the library, and data have public access. 

__Remark__: You lost the opportunity to name it `pynfo` :-P

**Comment by ofek** [comment]
the data is public which means anyone is authorized to access it, but you must still authenticate with Google cloud

**Comment by ofek** [comment]
Are these instructions and images insufficient? https://github.com/ofek/pypinfo#installation

**Comment by brunolnetto** [comment]
Oh, I did not scroll enough. Well played, sir.

**Comment by ofek** [comment]
Aha, maybe I should add a link to the anchor on top of the page

**Comment by brunolnetto** [comment]
I see my remark is useful after all. I suggest something like "Guided installation with pictures" os something like that

**Comment by ofek** [comment]
I'd be open to a PR if you're willing to!

**Comment by brunolnetto** [comment]
Is it ok if I add a collapsible on sections [likeso](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab)?

**Comment by ofek** [comment]
Just one around the example commands sounds fine

**Comment by brunolnetto** [comment]
I do not find a way to do it on raw restructuredText, just for Sphinx-based documentation. Have you ever seen something similar?

**Comment by ofek** [comment]
Oh true, it's okay I'll convert to Markdown eventually. Thanks for the suggestion!

**Comment by brunolnetto** [comment]
I will PR-push a markdown version. Is it ok?

**Comment by ofek** [comment]
sure

**Comment by brunolnetto** [comment]
I just pushed ea PR [here](https://github.com/ofek/pypinfo/pull/146)
