### ISSUE TITLE
Enforce "python 3 only" in setup.py

### ISSUE THREAD

**Issue by giampaolo** [ofek/pypinfo#25]
It is currently possible to install this package on Python 2 (via pip). It breaks when `pypinfo` is invoked from cmdline thought. I think `setup.py` should detect the Python version at runtime and prevent installing.

```
~/svn/smartfile/tp/python$ pypinfo
Traceback (most recent call last):
  File "/usr/local/bin/pypinfo", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/giampaolo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3142, in <module>
    @_call_aside
  File "/home/giampaolo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/home/giampaolo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/giampaolo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/giampaolo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 679, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/giampaolo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.2.2 (/home/giampaolo/.local/lib/python2.7/site-packages), Requirement.parse('pyasn1<0.4.0,>=0.3.4'), set(['pyasn1-modules']))
~/svn/smartfile/tp/python$ pypinfo
Traceback (most recent call last):
  File "/usr/local/bin/pypinfo", line 11, in <module>
    load_entry_point('pypinfo==5.0.0', 'console_scripts', 'pypinfo')()
  File "/home/giampaolo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/giampaolo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/giampaolo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/home/giampaolo/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/giampaolo/svn/pypinfo/pypinfo/cli.py", line 3, in <module>
    from pypinfo.core import build_query, create_client, format_json, parse_query_result, tabulate, add_percentages
  File "/home/giampaolo/svn/pypinfo/pypinfo/core.py", line 148
    headers, *data = rows
```

**Comment by hugovk** [comment]
See PR #26.
