### ISSUE TITLE
ModuleNotFoundError: No module named 'google.api_core'

### ISSUE THREAD

**Issue by hugovk** [ofek/pypinfo#31]
FYI, this is a Google problem, I've reported it here: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4395.

Short version:

```
[hugo:/tmp] 5s % python3
Python 3.6.0 (default, Mar  4 2017, 12:32:34)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from google.cloud import bigquery
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/cloud/bigquery/__init__.py", line 34, in <module>
    from google.cloud.bigquery._helpers import DEFAULT_RETRY
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/cloud/bigquery/_helpers.py", line 23, in <module>
    from google.api_core import retry
ModuleNotFoundError: No module named 'google.api_core'
>>>
```

Longer version:

After having done a recent `pip3 install -U pypinfo`:

```bash
[hugo:/tmp] % python3 --version
Python 3.6.0

[hugo:/tmp] 1 % pip3 --version
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)

[hugo:/tmp] 9s % pip3 install -U pypinfo
Requirement already up-to-date: pypinfo in /usr/local/lib/python3.6/site-packages
Requirement already up-to-date: click in /usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg (from pypinfo)
Requirement already up-to-date: tinydb in /usr/local/lib/python3.6/site-packages (from pypinfo)
Requirement already up-to-date: appdirs in /usr/local/lib/python3.6/site-packages/appdirs-1.4.3-py3.6.egg (from pypinfo)
Requirement already up-to-date: tinyrecord in /usr/local/lib/python3.6/site-packages/tinyrecord-0.1.3-py3.6.egg (from pypinfo)
Requirement already up-to-date: google-cloud-bigquery>=0.28.0 in /usr/local/lib/python3.6/site-packages (from pypinfo)
Requirement already up-to-date: google-api-core<0.2.0dev,>=0.1.1 in /usr/local/lib/python3.6/site-packages (from google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: requests>=2.18.0 in /usr/local/lib/python3.6/site-packages (from google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: google-cloud-core<0.29dev,>=0.28.0 in /usr/local/lib/python3.6/site-packages (from google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: google-auth>=1.0.0 in /usr/local/lib/python3.6/site-packages (from google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: google-resumable-media>=0.2.1 in /usr/local/lib/python3.6/site-packages (from google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: protobuf>=3.0.0 in /usr/local/lib/python3.6/site-packages/protobuf-3.4.0-py3.6.egg (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: googleapis-common-protos<2.0dev,>=1.5.3 in /usr/local/lib/python3.6/site-packages/googleapis_common_protos-1.5.3-py3.6.egg (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: six>=1.10.0 in /usr/local/lib/python3.6/site-packages (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: setuptools>=34.0.0 in /usr/local/lib/python3.6/site-packages (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.18.0->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.18.0->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.18.0->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.18.0->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: rsa>=3.1.4 in /usr/local/lib/python3.6/site-packages/rsa-3.4.2-py3.6.egg (from google-auth>=1.0.0->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: cachetools>=2.0.0 in /usr/local/lib/python3.6/site-packages/cachetools-2.0.1-py3.6.egg (from google-auth>=1.0.0->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.6/site-packages/pyasn1_modules-0.1.5-py3.6.egg (from google-auth>=1.0.0->google-cloud-bigquery>=0.28.0->pypinfo)
Requirement already up-to-date: pyasn1>=0.1.7 in /usr/local/lib/python3.6/site-packages/pyasn1-0.3.7-py3.6.egg (from google-auth>=1.0.0->google-cloud-bigquery>=0.28.0->pypinfo)

[hugo:/tmp] 2s % pip3 freeze | grep pypinfo
pypinfo==7.0.0

[hugo:/tmp] % pip3 freeze | grep google-cloud-bigquery
google-cloud-bigquery==0.28.0

[hugo:/tmp] % pip3 freeze | grep google
google-api-core==0.1.1
google-auth==1.2.1
google-cloud-bigquery==0.28.0
google-cloud-core==0.28.0
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3

[hugo:/tmp] % pypinfo pypinfo
Traceback (most recent call last):
  File "/usr/local/bin/pypinfo", line 7, in <module>
    from pypinfo.cli import pypinfo
  File "/usr/local/lib/python3.6/site-packages/pypinfo/cli.py", line 3, in <module>
    from pypinfo.core import (
  File "/usr/local/lib/python3.6/site-packages/pypinfo/core.py", line 5, in <module>
    from google.cloud.bigquery import Client
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/cloud/bigquery/__init__.py", line 34, in <module>
    from google.cloud.bigquery._helpers import DEFAULT_RETRY
  File "/usr/local/Cellar/python3/3.6.0_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/cloud/bigquery/_helpers.py", line 23, in <module>
    from google.api_core import retry
ModuleNotFoundError: No module named 'google.api_core'
```

**Comment by ofek** [comment]
No worries, thanks!
