### ISSUE TITLE
ImportError: cannot import name 'opentype'

### ISSUE THREAD

**Issue by noxdafox** [ofek/pypinfo#32]
From a fresh install

```
$ pypinfo --help

Traceback (most recent call last):
  File "/usr/local/bin/pypinfo", line 7, in <module>
    from pypinfo.cli import pypinfo
  File "/usr/local/lib/python3.5/dist-packages/pypinfo/cli.py", line 3, in <module>
    from pypinfo.core import (
  File "/usr/local/lib/python3.5/dist-packages/pypinfo/core.py", line 5, in <module>
    from google.cloud.bigquery import Client
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/bigquery/client.py", line 36, in <module>
    from google.cloud.client import ClientWithProject
  File "/usr/local/lib/python3.5/dist-packages/google/cloud/client.py", line 27, in <module>
    from google.oauth2 import service_account
  File "/usr/local/lib/python3.5/dist-packages/google/oauth2/service_account.py", line 77, in <module>
    from google.auth import _service_account_info
  File "/usr/local/lib/python3.5/dist-packages/google/auth/_service_account_info.py", line 22, in <module>
    from google.auth import crypt
  File "/usr/local/lib/python3.5/dist-packages/google/auth/crypt/__init__.py", line 39, in <module>
    from google.auth.crypt import rsa
  File "/usr/local/lib/python3.5/dist-packages/google/auth/crypt/rsa.py", line 17, in <module>
    from google.auth.crypt import _python_rsa
  File "/usr/local/lib/python3.5/dist-packages/google/auth/crypt/_python_rsa.py", line 29, in <module>
    from pyasn1_modules.rfc2459 import Certificate
  File "/usr/local/lib/python3.5/dist-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
ImportError: cannot import name 'opentype'
```

**Comment by hugovk** [comment]
In case this helps, I have these modules on Python 3.6.3 and it's working:

```bash
[hugo:/tmp] % pip freeze | grep google
google-api-core==0.1.1
google-auth==1.2.0
google-cloud-bigquery==0.28.0
google-cloud-core==0.28.0
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
[hugo:/tmp] 4s % pip freeze | grep pyasn1-modules
pyasn1-modules==0.1.5
```

Also after `pip install -U pypinfo`:

```bash
⌂67% [hugo:/tmp] % pip freeze | grep google
google-api-core==0.1.1
google-auth==1.2.1
google-cloud-bigquery==0.28.0
google-cloud-core==0.28.0
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
[hugo:/tmp] 2s % pip freeze | grep pyasn1-modules
pyasn1-modules==0.2.1
```

**Comment by hugovk** [comment]
I triggered a build of PR #23, which successfully ran `pypinfo --help` for Python 3.5 (and 3.6 and pypy3):

https://travis-ci.org/hugovk/pypinfo/builds/307807783

You can see which libraries are installed for Python 3.5 on the CI:

https://travis-ci.org/hugovk/pypinfo/jobs/307807786#L526

Please can you check which versions you have of the Google libraries and pyasn1-modules?

We might need to add more minimum versions in [setup.py](https://github.com/ofek/pypinfo/blob/master/setup.py#L44).

**Comment by noxdafox** [comment]
These are the installed libraries.

```
$ pip3 freeze | grep google

google-api-core==0.1.1
google-auth==1.2.1
google-cloud-bigquery==0.28.0
google-cloud-core==0.28.0
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3

$ pip3 freeze | grep pyasn1-modules
```

It's a fresh Debian Stretch installation (minimal).

**Comment by hugovk** [comment]
Those are the same as mine (macOS High Sierra) and Travis CI (Ubuntu Trusty). Does `pip3 install -U pypinfo` make any difference?

If not, have a look through https://github.com/etingof/pyasn1-modules/issues/10 which is likely the cause.

**Comment by noxdafox** [comment]
Yes, uprading to pyasn1 0.4.2 solved the issue. Probably the version restriction requires a bump.

Thanks for the swift help!

**Comment by hugovk** [comment]
pyasn1 isn't a direct dependency of pypinfo, it's something like pypinfo > google-cloud-bigquery > google-cloud-core > google-auth > pyasn1-modules > pyasn1.

Anyway, good you got it working and we know what to do if someone else runs in to it!

Perhaps we wait a bit for that dependency chain to sort themselves out (I'm not sure exactly where it comes from), or if this continues to be a problem perhaps we should include that as an explicit requirement (perhaps even temporarily).
