### ISSUE TITLE
SyntaxError: invalid syntax: headers, *data = rows: 

### ISSUE THREAD

**Issue by nschloe** [ofek/pypinfo#5]
I just pip-installed and I'm getting
```
Traceback (most recent call last):
  File "/usr/local/bin/pypinfo", line 7, in <module>
    from pypinfo.cli import pypinfo
  File "/usr/local/lib/python2.7/dist-packages/pypinfo/cli.py", line 3, in <module>
    from pypinfo.core import build_query, create_client, format_json, parse_query_result, tabulate
  File "/usr/local/lib/python2.7/dist-packages/pypinfo/core.py", line 118
    headers, *data = rows
             ^
SyntaxError: invalid syntax
```

**Comment by ofek** [comment]
@nschloe Thanks for your interest! Only Python 3 is supported; I'll make this more explicit in the docs.

Do `pip3 install --user pypinfo`

**Comment by nschloe** [comment]
The main README still says
```
pip install pypinfo
```
when really it should be
```
pip3 install pypinfo
```
