### ISSUE TITLE
YYYY-MM-DD dates issue in --start-date and --end-date

### ISSUE THREAD

**Issue by syhooper** [ofek/pypinfo#59]
I noticed that the date issue has been fixed in #49. However, I still can't use dates. Please see below. Could you please let me know how to use the start and end dates properly? Thanks! 

```console
$ pypinfo --start-date 2018-04-01 --end-date 2018-04-30 setuptools
Traceback (most recent call last):
  File "/anaconda3/bin/pypinfo", line 11, in <module>
    sys.exit(pypinfo())
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/pypinfo/cli.py", line 100, in pypinfo
    end_date=end_date, where=where, order=order_name, pip=pip
  File "/anaconda3/lib/python3.6/site-packages/pypinfo/core.py", line 56, in build_query
    if int(start_date) > 0 or int(end_date) > 0:
ValueError: invalid literal for int() with base 10: '2018-04-01'
```

**Comment by hugovk** [comment]
Hello!

`YYYY-MM-DD` dates were added in https://github.com/ofek/pypinfo/pull/49 but it hasn't been released yet.

In the meantime, you can install the latest development version:

```
pip install -U git+https://github.com/ofek/pypinfo.git
```

---

@ofek, please could you make a new release?

I'll also add version tags to Git which might help make things clearer too.

**Comment by ofek** [comment]
Sorry for the wait https://pypi.org/project/pypinfo/15.0.0
