### ISSUE TITLE
Installation failed: AttributeError: '_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by JakobDev** [ofek/pypinfo#78]
When I  try to install pypinfo, this happens:
```
jakob@Pluto:~$ sudo pip3 install pypinfo
[sudo] Passwort für jakob: 
WARNING: The directory '/home/jakob/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/jakob/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pypinfo
  Downloading https://files.pythonhosted.org/packages/19/f6/b62ba0fedb6638f20a453168d39c82878d01a06cb6829faebf1f8786f8a1/pypinfo-15.0.0-py2.py3-none-any.whl
Collecting google-cloud-bigquery>=0.29.0 (from pypinfo)
  Downloading https://files.pythonhosted.org/packages/89/1d/145b045a6bf8b3d1216f68b4ee55fe4932c24c2ee86c0dab971071dae6c5/google_cloud_bigquery-1.20.0-py2.py3-none-any.whl (154kB)
     |████████████████████████████████| 163kB 1.1MB/s 
Collecting appdirs (from pypinfo)
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from pypinfo) (6.2)
Collecting binary (from pypinfo)
  Downloading https://files.pythonhosted.org/packages/b4/ba/37de520e4870635793164a3d6861d98357d4e43aa6ce244327183ccaa3cb/binary-1.0.0-py2.py3-none-any.whl
Collecting tinyrecord (from pypinfo)
  Downloading https://files.pythonhosted.org/packages/62/5e/b69f5111206c85e7e4ed1824e8dd1fa216c6045ad812d45defc012557702/tinyrecord-0.1.5.tar.gz
Collecting tinydb (from pypinfo)
  Downloading https://files.pythonhosted.org/packages/dc/90/ced9f2a57513eb75dce70760e55967ceedbf2dc158b6a66f1bf87ac8fab0/tinydb-3.14.1-py2.py3-none-any.whl
Collecting google-cloud-core<2.0dev,>=1.0.3 (from google-cloud-bigquery>=0.29.0->pypinfo)
  Downloading https://files.pythonhosted.org/packages/ee/f0/084f598629db8e6ec3627688723875cdb03637acb6d86999bb105a71df64/google_cloud_core-1.0.3-py2.py3-none-any.whl
Collecting protobuf>=3.6.0 (from google-cloud-bigquery>=0.29.0->pypinfo)
  Downloading https://files.pythonhosted.org/packages/27/1c/ccf7810d5d02bdaafc223af032e8ac7f5ad6d23c5d0a44682a5a85fdda25/protobuf-3.10.0-cp35-cp35m-manylinux1_x86_64.whl (1.3MB)
     |████████████████████████████████| 1.3MB 531kB/s 
Collecting google-resumable-media>=0.3.1 (from google-cloud-bigquery>=0.29.0->pypinfo)
  Downloading https://files.pythonhosted.org/packages/96/d7/b29a41b01b854480891dfc408211ffb0cc7a2a3d5f15a3b6740ec18c845b/google_resumable_media-0.4.1-py2.py3-none-any.whl
Collecting google-api-core<2.0.0dev,>=1.14.0 (from google-cloud-core<2.0dev,>=1.0.3->google-cloud-bigquery>=0.29.0->pypinfo)
  Downloading https://files.pythonhosted.org/packages/29/3a/c528ef37f48d6ffba16f0f3c0426456ba21e0dd32be9c61a2ade93e07faa/google_api_core-1.14.3-py2.py3-none-any.whl (68kB)
     |████████████████████████████████| 71kB 1.0MB/s 
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from protobuf>=3.6.0->google-cloud-bigquery>=0.29.0->pypinfo) (20.7.0)
Requirement already satisfied: six>=1.9 in ./.local/lib/python3.5/site-packages (from protobuf>=3.6.0->google-cloud-bigquery>=0.29.0->pypinfo) (1.12.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.5/dist-packages (from google-api-core<2.0.0dev,>=1.14.0->google-cloud-core<2.0dev,>=1.0.3->google-cloud-bigquery>=0.29.0->pypinfo) (2.22.0)
Collecting googleapis-common-protos<2.0dev,>=1.6.0 (from google-api-core<2.0.0dev,>=1.14.0->google-cloud-core<2.0dev,>=1.0.3->google-cloud-bigquery>=0.29.0->pypinfo)
  Downloading https://files.pythonhosted.org/packages/eb/ee/e59e74ecac678a14d6abefb9054f0bbcb318a6452a30df3776f133886d7d/googleapis-common-protos-1.6.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "/usr/lib/python3/dist-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-33ap899x/googleapis-common-protos/
WARNING: You are using pip version 19.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
jakob@Pluto:~$ 
```

**Comment by hugovk** [comment]
Please can you do this and then try again?

```
pip install --upgrade pip setuptools
```

(Suggested at https://github.com/googleapis/google-cloud-python/issues/2990)

**Comment by JakobDev** [comment]
Upgrading setuptools was the solution. Thanks!
