### ISSUE TITLE
sytematic error when i use --auth

### ISSUE THREAD

**Issue by Pacidus** [ofek/pypinfo#88]
When i run  ``` pypinfo --auth key.json ``` with the BigQuery key i have the given answer :

```console
$ pypinfo --auth key.json
Traceback (most recent call last):
  File "~/.local/bin/pypinfo", line 8, in <module>
    sys.exit(pypinfo())
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/pypinfo/cli.py", line 119, in pypinfo
    set_credentials(auth)
  File "~/.local/lib/python3.8/site-packages/pypinfo/db.py", line 25, in set_credentials
    tr.insert({'path': creds_file})
  File "~/.local/lib/python3.8/site-packages/tinyrecord/transaction.py", line 86, in __exit__
    self.record.execute()
  File "~/.local/lib/python3.8/site-packages/tinyrecord/changeset.py", line 21, in execute
    data = self.db._read()
AttributeError: 'Table' object has no attribute '_read'
```
There is probably something about tinydb package

**Comment by ofek** [comment]
@Pacidus Thanks!

@hugovk Mind taking a look? I'm not feeling very well.

**Comment by hugovk** [comment]
Sure, will check it later.

**Comment by hugovk** [comment]
It's working for me:
```console
$ pypinfo --auth /Users/hugo/pypinfo.json
Credentials location set to "/Users/hugo/pypinfo.json".
```
My JSON file is of this format:
```json
{
  "type": "service_account",
  "project_id": "p<snip>k",
  "private_key_id": "e<snip>7",
  "private_key": "-----BEGIN PRIVATE KEY-----\nM4<snip>Vg4=\n-----END PRIVATE KEY-----\n",
  "client_email": "pypinfo@p<snip>k.iam.gserviceaccount.com",
  "client_id": "1<snip>8",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/pypinfo%40p<snip>k.iam.gserviceaccount.com"
}
```
Is your JSON similar to this?

And what do you get when running this?

```sh
pip freeze | grep -i appdirs
pip freeze | grep -i binary
pip freeze | grep -i click
pip freeze | grep -i google-cloud-bigquery
pip freeze | grep -i tinydb
pip freeze | grep -i tinyrecord
```

I get:
```
appdirs==1.4.3
binary==1.0.0
click==7.1.2
google-cloud-bigquery==1.23.1
tinydb==3.15.2
tinyrecord==0.1.5
```

**Comment by hugovk** [comment]
And you were right, it is something in tinydb: `pip install "tinydb<4"` is a workaround for now.

**Comment by hugovk** [comment]
Or rather, tinyrecord isn't yet compatible with the tinydb's breaking changes. I've reported it at https://github.com/eugene-eeo/tinyrecord/issues/11.

Shall we wait a bit for a fix, and then release with deps `tinydb>=4` and `tinyrecord>=[the fixed version]`?

And if there's no fix for a while, we could make a workaround release with `tinydb<4`?

**Comment by Pacidus** [comment]
> And you were right, it is something in tinydb: `pip install "tinydb<4"` is a workaround for now.

Thanks this solved the error.
