### ISSUE TITLE
Fresh installation - first query fails with an exception

### ISSUE THREAD

**Issue by vsajip** [ofek/pypinfo#97]
I just created a brand-new venv `pypistats` and installed `pypinfo` into it. Running a query from the examples results in an exception:

```
pypistats ~/projects/pypistats  $ pip install pypinfo
Collecting pypinfo
  Downloading pypinfo-16.0.1-py3-none-any.whl (13 kB)
Collecting tinyrecord
  Downloading tinyrecord-0.2.0.tar.gz (5.6 kB)
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 89 kB/s 
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting binary
  Downloading binary-1.0.0-py2.py3-none-any.whl (9.2 kB)
Collecting tinydb<4
  Downloading tinydb-3.15.2-py2.py3-none-any.whl (17 kB)
Collecting google-cloud-bigquery>=0.29.0
  Downloading google_cloud_bigquery-1.25.0-py2.py3-none-any.whl (169 kB)
     |████████████████████████████████| 169 kB 257 kB/s 
Collecting google-cloud-core<2.0dev,>=1.1.0
  Downloading google_cloud_core-1.3.0-py2.py3-none-any.whl (26 kB)
Collecting google-api-core<2.0dev,>=1.15.0
  Downloading google_api_core-1.21.0-py2.py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 276 kB/s 
Collecting google-resumable-media<0.6dev,>=0.5.0
  Downloading google_resumable_media-0.5.1-py2.py3-none-any.whl (38 kB)
Collecting six<2.0.0dev,>=1.13.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting protobuf>=3.6.0
  Downloading protobuf-3.12.2-cp38-cp38-manylinux1_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 289 kB/s 
Collecting google-auth<2.0dev,>=1.9.0
  Downloading google_auth-1.18.0-py2.py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 259 kB/s 
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Downloading googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 236 kB/s 
Collecting requests<3.0.0dev,>=2.18.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: setuptools>=34.0.0 in /disk2/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages (from google-api-core<2.0dev,>=1.15.0->google-cloud-bigquery>=0.29.0->pypinfo) (49.2.0)
Collecting pytz
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 295 kB/s 
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.1.1-py3-none-any.whl (10 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 291 kB/s 
Collecting rsa<5,>=3.1.4; python_version >= "3"
  Downloading rsa-4.6-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 322 kB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 332 kB/s 
Building wheels for collected packages: tinyrecord
  Building wheel for tinyrecord (setup.py) ... done
  Created wheel for tinyrecord: filename=tinyrecord-0.2.0-py3-none-any.whl size=5906 sha256=bfc555a6e38a138609331d3157f564ed452ff519560fbfccca8121062c8dee87
  Stored in directory: /home/vinay/.cache/pip/wheels/f7/70/8f/ed3793264c07aff8cc7bd7236be77becc24c410f976ee6fc55
Successfully built tinyrecord
Installing collected packages: tinyrecord, click, appdirs, binary, tinydb, cachetools, pyasn1, pyasn1-modules, rsa, six, google-auth, protobuf, googleapis-common-protos, urllib3, idna, chardet, certifi, requests, pytz, google-api-core, google-cloud-core, google-resumable-media, google-cloud-bigquery, pypinfo
Successfully installed appdirs-1.4.4 binary-1.0.0 cachetools-4.1.1 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 google-api-core-1.21.0 google-auth-1.18.0 google-cloud-bigquery-1.25.0 google-cloud-core-1.3.0 google-resumable-media-0.5.1 googleapis-common-protos-1.52.0 idna-2.10 protobuf-3.12.2 pyasn1-0.4.8 pyasn1-modules-0.2.8 pypinfo-16.0.1 pytz-2020.1 requests-2.24.0 rsa-4.6 six-1.15.0 tinydb-3.15.2 tinyrecord-0.2.0 urllib3-1.25.9
pypistats ~/projects/pypistats  $ pypinfo --auth pypi-stats.json --days 365 "" project
Traceback (most recent call last):
  File "/home/vinay/.local/share/virtualenvs/pypistats/bin/pypinfo", line 8, in <module>
    sys.exit(pypinfo())
  File "/home/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages/pypinfo/cli.py", line 119, in pypinfo
    set_credentials(auth)
  File "/home/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages/pypinfo/db.py", line 25, in set_credentials
    tr.insert({'path': creds_file})
  File "/home/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages/tinyrecord/transaction.py", line 79, in __exit__
    self.record.execute()
  File "/home/vinay/.local/share/virtualenvs/pypistats/lib/python3.8/site-packages/tinyrecord/changeset.py", line 25, in execute
    self.table._update_table(updater)
AttributeError: 'Table' object has no attribute '_update_table'
```

**Comment by hugovk** [comment]
Here's a workaround:

```sh
pip install "tinyrecord<0.2.0"
````

Please could you try that?

---

We should make a new release of pypinfo too.

Background:

There had been a new release of dependency TinyDB (v4), but another dependency Tinyrecord didn't yet support the new TinyDB so we pinned TinyDB to <4 (https://github.com/ofek/pypinfo/pull/89). 

There's since been a new release of Tinyrecord (v0.2.0) that supports TinyDB v4, but not TinyDB <4. (We should have pinned both. Next time! :)

Anyway, we've now set minimum versions of both TinyDB >=4 and Tinyrecord >=0.2.0 (https://github.com/ofek/pypinfo/pull/96), and need to release this.

**Comment by ofek** [comment]
@hugovk Can you release and I'll upload it?

**Comment by hugovk** [comment]
Yes, the last release was 16.0.1, should this be 16.0.2 or 17.0.0?

Take your pick from these PRs :)

* https://github.com/ofek/pypinfo/pull/98: 16.0.2
* https://github.com/ofek/pypinfo/pull/99: 17.0.0

**Comment by ofek** [comment]
https://pypi.org/project/pypinfo/16.0.2/
